make getjq run first on all environments

diff --git a/run_stubs b/run_stubs
--- a/run_stubs
+++ b/run_stubs
@@ -41,26 +41,32 @@ if ! echo "$PATH" | grep -q "$HOME/bin/ln" ; then
     fi
 fi
 
-for i in "$RESTORE/stubs/"* ; do
-    if ! [ -e "$i" ] ; then
-        echo "${RED}Error: $i does not exist${RESET}" >&2
-        continue
-    fi
-    if ! head -1 "$i" | grep -q '^#!/usr/bin/env bash'; then
-        continue
-    fi
-    echo "${GREEN}running $i${RESET}" >&2
-
-    pushd "$RESTORE/stubs" > /dev/null|| panic
-    if ! $i ; then
-        echo "${RED}Error: $i failed.${RESET}" >&2
-        read -p "${RED}Continue? [y/N] ${RESET}" -n 1 -r
-        echo
-        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
-            panic
+run_batch() {
+    for i in "$RESTORE/$1/"* ; do
+        if ! [ -e "$i" ] ; then
+            echo "${RED}Error: $i does not exist${RESET}" >&2
+            continue
         fi
-    fi
-    popd > /dev/null || panic
-done
+        if ! head -1 "$i" | grep -q '^#!/usr/bin/env bash'; then
+            continue
+        fi
+        echo "${GREEN}running $i${RESET}" >&2
+
+        pushd "$RESTORE/$1" > /dev/null || panic
+        chmod +x "$i"
+        if ! $i ; then
+            echo "${RED}Error: $i failed.${RESET}" >&2
+            read -p "${RED}Continue? [y/N] ${RESET}" -n 1 -r
+            echo
+            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+                panic
+            fi
+        fi
+        popd > /dev/null || panic
+    done
+}
+
+run_batch "preinstall"
+run_batch "stubs"
 
 cd "$RESTORE" || panic
